services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama/data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    entrypoint:
      - /bin/bash
      - -c
      - "ollama serve & sleep 5 && ollama run llama3.2 && wait"
  mcp-server:
    image: amazoncorretto:21-al2023-headless
    ports:
      - "8080:8080"
    volumes:
      - ./mcp-server/build/libs/:/root/mcp-server
    entrypoint:
      - java
      - -jar
      - /root/mcp-server/mcp-server.jar

  mcphost:
    container_name: mcphost
    build:
      context: ./mcphost
    profiles:
      - manual
